#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Herofis <-> Glass Cutting Program integration API blueprint.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List
from uuid import uuid4

from flask import Blueprint, jsonify, request

from modules import (
    CuttingPathOptimizer,
    GlassType,
    NC300GCodeGenerator,
    NestingAlgorithm,
    NestingOptimizer,
    Part,
    PathAlgorithm,
)
from modules.herofis_connector import HerofisConnector
from web.backend.integration_store import IntegrationStore


def _utc_timestamp() -> str:
    return datetime.now(timezone.utc).isoformat()


def _sample_payload(order_id: str) -> Dict[str, Any]:
    numeric_tail = "".join(ch for ch in str(order_id) if ch.isdigit()) or "1"
    return {
        "order": {
            "orderId": str(order_id),
            "orderNo": f"GC-2026-{int(numeric_tail):05d}",
            "customerId": "1000002",
            "customerName": "Abt Cam A.S.",
            "deliveryDate": "2026-04-15",
            "deliveryType": 1,
            "deliveryAddress": "Istanbul Tuzla OSB",
            "packageType": 2,
            "currency": "TRY",
            "orderNote": "MVP sample payload generated by integration API",
        },
        "lines": [
            {
                "lineId": f"{order_id}-1",
                "rowNo": 1,
                "stockId": "501",
                "stockCode": "ISICAM-4-16-4",
                "stockName": "Isicam 4+16+4",
                "formulaCode": "4-16-4",
                "processCode": "TEMPER_LOWE",
                "groupCode": "GRP-01",
                "width": 1200,
                "height": 1800,
                "quantity": 8,
                "unit": "ADET",
                "lineNote": "Blue label",
                "glassItems": [
                    {"itemType": "glass", "code": "GLASS-4MM", "name": "4mm Clear", "thickness": 4},
                    {"itemType": "spacer", "code": "SP16", "name": "16mm Spacer", "thickness": 16},
                    {"itemType": "glass", "code": "GLASS-4MM-LOWE", "name": "4mm LowE", "thickness": 4},
                ],
            }
        ],
        "meta": {
            "source": "herofis-camcad",
            "moduleNo": 761,
            "exportedAt": _utc_timestamp(),
            "integrationVersion": "1.0",
        },
    }


def _normalize_glass_type(line: Dict[str, Any]) -> str:
    text = " ".join(
        str(value)
        for value in [
            line.get("stockName", ""),
            line.get("processCode", ""),
            json.dumps(line.get("glassItems", []), ensure_ascii=False),
        ]
    ).lower()
    if "lamine" in text or "laminated" in text or "film" in text:
        return "laminated"
    if "temper" in text:
        return "tempered"
    return "float"


def _run_local_payload_optimization(base_dir: Path, payload: Dict[str, Any]) -> Dict[str, Any]:
    machine_width = 6000
    machine_height = 3000
    parts: List[Part] = []
    detected_glass_type = GlassType.FLOAT
    for line in payload.get("lines", []):
        line_glass_type = _normalize_glass_type(line)
        if line_glass_type == GlassType.LAMINATED.value:
            detected_glass_type = GlassType.LAMINATED
        elif line_glass_type == GlassType.TEMPERED.value and detected_glass_type != GlassType.LAMINATED:
            detected_glass_type = GlassType.TEMPERED
        quantity = int(float(line.get("quantity", 1) or 1))
        for index in range(quantity):
            parts.append(
                Part(
                    part_id=f"{line.get('lineId')}-{index + 1}",
                    width=float(line.get("width", 0) or 0),
                    height=float(line.get("height", 0) or 0),
                    thickness=4.0,
                    priority=1,
                    rotate_allowed=True,
                    glass_type=line_glass_type,
                )
            )

    if not parts:
        raise ValueError("No line items available for optimization")

    optimizer = NestingOptimizer(machine_width, machine_height, NestingAlgorithm.GUILLOTINE_BESTFIT)
    nesting_result = optimizer.optimize(parts)

    path_optimizer = CuttingPathOptimizer(machine_width, machine_height)
    path_result = path_optimizer.optimize(nesting_result["placed_parts"], PathAlgorithm.TWO_OPT)

    gcode_gen = NC300GCodeGenerator()
    gcode_program = gcode_gen.generate(
        nesting_result["placed_parts"],
        path_result["path"],
        detected_glass_type,
        f"live_{payload.get('order', {}).get('orderNo', 'order')}",
    )
    gcode_file = gcode_gen.save_to_file(gcode_program, str(base_dir / "output" / "gcode"))

    line_results = []
    for line in payload.get("lines", []):
        matching = [p for p in nesting_result["placed_parts"] if str(p.get("part_id", "")).startswith(str(line.get("lineId")))]
        line_results.append(
            {
                "lineId": line.get("lineId"),
                "optimized": len(matching) > 0,
                "assignedBatchNo": "LOCAL-BATCH-01",
                "sheetCount": 1 if matching else 0,
                "wasteArea": None,
                "efficiency": round(nesting_result["utilization"] * 100, 2),
            }
        )

    return {
        "summary": {
            "totalSheetsUsed": 1,
            "totalWasteArea": round(float(nesting_result["waste_area"]) / 1_000_000, 4),
            "efficiency": round(float(nesting_result["utilization"]) * 100, 2),
        },
        "lineResults": line_results,
        "files": [
            {
                "type": "machine-export",
                "name": Path(gcode_file).name,
                "url": str(gcode_file),
            }
        ],
        "engine": "local-guillotine-2opt",
        "glassType": detected_glass_type.value,
        "placedParts": len(nesting_result["placed_parts"]),
        "totalCuts": len(nesting_result["placed_parts"]),
        "estimatedTime": round(float(path_result["total_distance"]) / 1000, 2),
    }


def create_integration_blueprint(base_dir: Path) -> Blueprint:
    base_dir = Path(base_dir)
    store = IntegrationStore(base_dir)
    connector = HerofisConnector(data_dir=str(base_dir / "data" / "herofis"))
    bp = Blueprint("integration_api", __name__)

    @bp.route("/api/herofis/import-csv", methods=["POST"])
    def import_herofis_csv():
        data = request.get_json(silent=True) or {}
        file_path = str(data.get("filePath") or "").strip()
        if not file_path:
            return jsonify({"success": False, "error": "filePath is required"}), 400

        result = connector.import_csv(
            file_path=file_path,
            encoding=str(data.get("encoding") or "auto"),
            delimiter=str(data.get("delimiter") or "auto"),
            skip_header=bool(data.get("skipHeader", True)),
        )
        if not result.success:
            return jsonify(
                {
                    "success": False,
                    "errors": result.errors,
                    "warnings": result.warnings,
                    "importedRows": result.imported_rows,
                    "skippedRows": result.skipped_rows,
                }
            ), 400

        payloads = connector.build_payloads_by_order(result.orders)
        return jsonify(
            {
                "success": True,
                "sourceFile": result.source_file,
                "importedRows": result.imported_rows,
                "skippedRows": result.skipped_rows,
                "orderCount": len(payloads),
                "orderNos": list(payloads.keys()),
                "payloads": payloads,
            }
        )

    @bp.route("/api/herofis/import-json", methods=["POST"])
    def import_herofis_json():
        data = request.get_json(silent=True) or {}
        file_path = str(data.get("filePath") or "").strip()
        if not file_path:
            return jsonify({"success": False, "error": "filePath is required"}), 400

        result = connector.import_json(file_path=file_path)
        if not result.success:
            return jsonify({"success": False, "errors": result.errors}), 400

        payloads = connector.build_payloads_by_order(result.orders)
        return jsonify(
            {
                "success": True,
                "sourceFile": result.source_file,
                "importedRows": result.imported_rows,
                "skippedRows": result.skipped_rows,
                "orderCount": len(payloads),
                "orderNos": list(payloads.keys()),
                "payloads": payloads,
            }
        )

    @bp.route("/api/herofis/fetch-json", methods=["POST"])
    def fetch_herofis_json():
        data = request.get_json(silent=True) or {}
        url = str(data.get("url") or "").strip()
        if not url:
            return jsonify({"success": False, "error": "url is required"}), 400

        headers = data.get("headers") or {}
        try:
            fetched = connector.fetch_orders_json(url=url, headers=headers, timeout=int(data.get("timeout", 30)))
        except Exception as exc:
            return jsonify({"success": False, "error": str(exc)}), 400

        return jsonify({"success": True, "data": fetched})

    @bp.route("/api/herofis/fetch-live-order", methods=["POST"])
    def fetch_live_herofis_order():
        data = request.get_json(silent=True) or {}
        username = str(data.get("username") or "").strip()
        password = str(data.get("password") or "").strip()
        order_no = str(data.get("orderNo") or "").strip()
        base_url = str(data.get("baseUrl") or "https://herofis.com").strip()

        if not username or not password or not order_no:
            return jsonify({"success": False, "error": "username, password and orderNo are required"}), 400

        try:
            payload = connector.fetch_live_order_payload(
                username=username,
                password=password,
                order_no=order_no,
                base_url=base_url,
                verify_ssl=bool(data.get("verifySsl", True)),
            )
        except Exception as exc:
            return jsonify({"success": False, "error": str(exc)}), 400

        return jsonify({"success": True, "payload": payload})

    @bp.route("/api/herofis/update-live-status", methods=["POST"])
    def update_live_herofis_status():
        data = request.get_json(silent=True) or {}
        username = str(data.get("username") or "").strip()
        password = str(data.get("password") or "").strip()
        live_order_id = data.get("liveOrderId")
        status_id = data.get("statusId")
        order_no = str(data.get("orderNo") or "").strip() or None
        base_url = str(data.get("baseUrl") or "https://herofis.com").strip()
        verify_ssl = bool(data.get("verifySsl", True))
        remarks = str(data.get("remarks") or "")

        if not username or not password or live_order_id is None or status_id is None:
            return jsonify({"success": False, "error": "username, password, liveOrderId and statusId are required"}), 400

        try:
            result = connector.update_live_order_status(
                username=username,
                password=password,
                live_order_id=int(live_order_id),
                status_id=int(status_id),
                order_no=order_no,
                remarks=remarks,
                base_url=base_url,
                verify_ssl=verify_ssl,
            )
        except Exception as exc:
            return jsonify({"success": False, "error": str(exc)}), 400

        return jsonify(result)

    @bp.route("/api/orders/export-to-optimizer", methods=["POST"])
    def export_to_optimizer():
        data = request.get_json(silent=True) or {}
        order_id = str(data.get("orderId") or "").strip()
        herofis_file_path = str(data.get("herofisFilePath") or "").strip()
        herofis_json_path = str(data.get("herofisJsonPath") or "").strip()
        herofis_live = bool(data.get("herofisLive", False))
        herofis_order_no = str(data.get("herofisOrderNo") or order_id).strip()

        if not order_id and not ((herofis_file_path or herofis_json_path or herofis_live) and herofis_order_no):
            return jsonify({"success": False, "error": "orderId is required"}), 400

        if herofis_file_path:
            import_result = connector.import_csv(
                file_path=herofis_file_path,
                encoding=str(data.get("encoding") or "auto"),
                delimiter=str(data.get("delimiter") or "auto"),
                skip_header=bool(data.get("skipHeader", True)),
            )
            if not import_result.success:
                return jsonify({"success": False, "error": "Herofis import failed", "details": import_result.errors}), 400
            payloads = connector.build_payloads_by_order(import_result.orders)
            if herofis_order_no not in payloads:
                return jsonify(
                    {
                        "success": False,
                        "error": f"Order not found in Herofis file: {herofis_order_no}",
                        "availableOrders": list(payloads.keys()),
                    }
                ), 404
            order_id = herofis_order_no
            payload = payloads[herofis_order_no]
        elif herofis_json_path:
            import_result = connector.import_json(file_path=herofis_json_path)
            if not import_result.success:
                return jsonify({"success": False, "error": "Herofis JSON import failed", "details": import_result.errors}), 400
            payloads = connector.build_payloads_by_order(import_result.orders)
            if herofis_order_no not in payloads:
                return jsonify(
                    {
                        "success": False,
                        "error": f"Order not found in Herofis JSON: {herofis_order_no}",
                        "availableOrders": list(payloads.keys()),
                    }
                ), 404
            order_id = herofis_order_no
            payload = payloads[herofis_order_no]
        elif herofis_live:
            username = str(data.get("username") or "").strip()
            password = str(data.get("password") or "").strip()
            if not username or not password:
                return jsonify({"success": False, "error": "username and password are required for live Herofis export"}), 400
            try:
                payload = connector.fetch_live_order_payload(
                    username=username,
                    password=password,
                    order_no=herofis_order_no,
                    base_url=str(data.get("baseUrl") or "https://herofis.com").strip(),
                    verify_ssl=bool(data.get("verifySsl", True)),
                )
            except Exception as exc:
                return jsonify({"success": False, "error": str(exc)}), 400
            order_id = str(payload.get("order", {}).get("orderNo") or herofis_order_no)
        else:
            payload = data.get("payload") or _sample_payload(order_id)

        order_no = (
            data.get("orderNo")
            or payload.get("order", {}).get("orderNo")
            or f"GC-{order_id}"
        )
        job_id = data.get("jobId") or f"JOB-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}-{uuid4().hex[:6].upper()}"
        triggered_by = data.get("triggeredBy") or "system"
        force_reoptimize = bool(data.get("forceReoptimize", False))

        store.create_job(
            job_id=job_id,
            order_id=order_id,
            order_no=str(order_no),
            triggered_by=str(triggered_by),
            force_reoptimize=force_reoptimize,
            status="queued",
        )
        store.save_payload(job_id=job_id, order_id=order_id, payload=payload)
        store.update_job_status(job_id, "payload_ready")

        return jsonify(
            {
                "success": True,
                "jobId": job_id,
                "orderId": order_id,
                "orderNo": order_no,
                "status": "payload_ready",
                "nextAction": "send_to_optimizer",
            }
        )

    @bp.route("/api/orders/<order_id>/export-payload", methods=["GET"])
    def get_export_payload(order_id: str):
        payload = store.get_latest_payload(order_id) or _sample_payload(order_id)
        return jsonify(payload)

    @bp.route("/api/optimizations/result", methods=["POST"])
    def save_optimization_result():
        data = request.get_json(silent=True) or {}
        required = ["jobId", "orderId", "optimizationRunId", "status"]
        missing = [field for field in required if not data.get(field)]
        if missing:
            return jsonify({"success": False, "error": f"Missing required fields: {', '.join(missing)}"}), 400

        result_payload = {
            "jobId": str(data["jobId"]),
            "orderId": str(data["orderId"]),
            "optimizationRunId": str(data["optimizationRunId"]),
            "status": str(data["status"]),
            "summary": data.get("summary", {}),
            "lineResults": data.get("lineResults", []),
            "files": data.get("files", []),
            "message": data.get("message"),
            "optimizedAt": data.get("optimizedAt") or _utc_timestamp(),
        }
        store.save_optimization_result(result_payload)
        auto_mark = bool(data.get("autoMarkOptimized", False))
        if auto_mark:
            store.mark_order_optimized(
                order_id=result_payload["orderId"],
                optimization_run_id=result_payload["optimizationRunId"],
                updated_by=str(data.get("updatedBy") or "system"),
            )

        return jsonify(
            {
                "success": True,
                "orderId": result_payload["orderId"],
                "optimizationRunId": result_payload["optimizationRunId"],
                "status": "marked_in_herofis" if auto_mark else "result_saved",
            }
        )

    @bp.route("/api/optimizations/<optimization_run_id>", methods=["GET"])
    def get_optimization_result(optimization_run_id: str):
        result = store.get_optimization_result(optimization_run_id)
        if not result:
            return jsonify({"success": False, "error": "Optimization result not found"}), 404
        return jsonify(result)

    @bp.route("/api/orders/<order_id>/mark-optimized", methods=["POST"])
    def mark_order_optimized(order_id: str):
        data = request.get_json(silent=True) or {}
        optimization_run_id = str(data.get("optimizationRunId") or "").strip()
        if not optimization_run_id:
            return jsonify({"success": False, "error": "optimizationRunId is required"}), 400

        updated_by = str(data.get("updatedBy") or "system")
        store.mark_order_optimized(order_id, optimization_run_id, updated_by)
        return jsonify(
            {
                "success": True,
                "orderId": order_id,
                "optimizationRunId": optimization_run_id,
                "status": "marked_in_herofis",
            }
        )

    @bp.route("/api/integration/jobs/<job_id>", methods=["GET"])
    def get_job(job_id: str):
        job = store.get_job(job_id)
        if not job:
            return jsonify({"success": False, "error": "Job not found"}), 404
        return jsonify({"success": True, "job": job})

    @bp.route("/api/integration/herofis-live-optimize", methods=["POST"])
    def herofis_live_optimize():
        data = request.get_json(silent=True) or {}
        username = str(data.get("username") or "").strip()
        password = str(data.get("password") or "").strip()
        order_no = str(data.get("orderNo") or "").strip()
        triggered_by = str(data.get("triggeredBy") or username or "system")
        base_url = str(data.get("baseUrl") or "https://herofis.com").strip()
        verify_ssl = bool(data.get("verifySsl", True))
        auto_mark = bool(data.get("autoMarkOptimized", True))
        target_status_id = data.get("targetStatusId", 20)
        status_update = None

        if not username or not password or not order_no:
            return jsonify({"success": False, "error": "username, password and orderNo are required"}), 400

        try:
            payload = connector.fetch_live_order_payload(
                username=username,
                password=password,
                order_no=order_no,
                base_url=base_url,
                verify_ssl=verify_ssl,
            )
        except Exception as exc:
            return jsonify({"success": False, "error": f"Live fetch failed: {exc}"}), 400

        job_id = f"JOB-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}-{uuid4().hex[:6].upper()}"
        order_id = str(payload.get("order", {}).get("orderNo") or order_no)
        store.create_job(
            job_id=job_id,
            order_id=order_id,
            order_no=order_id,
            triggered_by=triggered_by,
            force_reoptimize=bool(data.get("forceReoptimize", False)),
            status="queued",
        )
        store.save_payload(job_id=job_id, order_id=order_id, payload=payload)
        store.update_job_status(job_id, "payload_ready")

        try:
            optimization = _run_local_payload_optimization(base_dir, payload)
        except Exception as exc:
            store.update_job_status(job_id, "failed", str(exc))
            return jsonify({"success": False, "error": f"Optimization failed: {exc}", "jobId": job_id}), 500

        optimization_run_id = f"OPT-{order_id}-{uuid4().hex[:6].upper()}"
        result_payload = {
            "jobId": job_id,
            "orderId": order_id,
            "optimizationRunId": optimization_run_id,
            "status": "optimized",
            "summary": optimization["summary"],
            "lineResults": optimization["lineResults"],
            "files": optimization["files"],
            "message": "Live Herofis order optimized with local engine",
            "optimizedAt": _utc_timestamp(),
        }
        store.save_optimization_result(result_payload)
        if auto_mark:
            store.mark_order_optimized(order_id, optimization_run_id, triggered_by)

        if target_status_id is not None:
            try:
                status_update = connector.update_live_order_status(
                    username=username,
                    password=password,
                    live_order_id=int(payload["meta"]["liveOrderId"]),
                    status_id=int(target_status_id),
                    order_no=order_no,
                    base_url=base_url,
                    verify_ssl=verify_ssl,
                    remarks=str(data.get("statusRemarks") or ""),
                )
            except Exception as exc:
                store.update_job_status(job_id, "failed", f"Status update failed: {exc}")
                return jsonify(
                    {
                        "success": False,
                        "jobId": job_id,
                        "optimizationRunId": optimization_run_id,
                        "error": f"Optimization succeeded but Herofis status update failed: {exc}",
                    }
                ), 500

        return jsonify(
            {
                "success": True,
                "jobId": job_id,
                "orderId": order_id,
                "optimizationRunId": optimization_run_id,
                "status": "marked_in_herofis" if auto_mark else "result_saved",
                "summary": optimization["summary"],
                "files": optimization["files"],
                "placedParts": optimization["placedParts"],
                "estimatedTime": optimization["estimatedTime"],
                "engine": optimization["engine"],
                "statusUpdate": status_update,
            }
        )

    return bp
