; ================================================
; LiSEC GFB-60/30RE Glass Cutting Program
; Generated by AI GlassCuttingProgram
; Date: 2026-04-13T09:41:33.722155
; Program: blade_delete_demo
; ================================================

; Glass type: float
; Parts count: 1

; --- Machine Initialization ---
G21
G90
G17

; --- Safety Check ---
; Verify sheet position
; Verify coolant (if required)

; --- Start Cutting ---
M03 S1000


; --- Part: BLADE-DELETE-001 ---
; Position: (450.00, 320.00)
; Size: 900x650 mm
; Thickness: 4.0 mm
G00 X450.00 Y320.00 F80000

; Blade delete sequence
; Step BD1: Move to wiping pad
G00 X370.00 Y260.00 F80000
M10
G04 P1.5 ; Blade wipe contact
M11
; Step BD2: Return to cut start
G00 X450.00 Y320.00 F80000
G01 X1350.00 Y320.00 F1000
G01 X1350.00 Y970.00
G01 X450.00 Y970.00
G01 X450.00 Y320.00

; --- End Cutting ---
M05

; Return to home
G00 X0 Y0

M30

; --- End of Program ---